service:
  name: aws-nodejs

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  region: ap-southeast-2
  environment:
    API_KEY: "1234"

package:
  exclude:
    - "**/**.test.*"

functions:
  index:
    handler: index.post
    events:
      - http:
          method: post
          path: index
          cors:
            origin: "*"
            headers:
              - X-Serverless-Warmup
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
