service:
  name: aws-nodejs

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: ap-southeast-2
  logRetentionInDays: 14 # Set the default RetentionInDays for a CloudWatch LogGroup
  environment:
    API_KEY: "1234"

package:
  exclude:
    - "**/**.test.*"

functions:
  index:
    handler: index.post
    events:
      - http:
          method: post
          path: index
          cors:
            origin: "*"
            # origins:
            # - http://localhost:*
            # - https://test.com
            headers:
              - X-Serverless-Warmup
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
