service:
  name: aws-nodejs

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  region: ap-southeast-2
  environment:
    API_KEY: "1234"

functions:
  index:
    handler: index.post
    events:
      - http:
          method: post
          path: index
          cors:
            origin: "*"
            headers:
              - "X-Serverless-Warmup"
              - "Content-Type"
